---
# title: "Data Sources"
# author: "Tammy"
# date: "April 16, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(DT)
```

# Data Sources

There are many data sources that feed into Portal. The tables below provide a description of each source.

_Last update: 2016-11-03_

```{r data-sources-table.csv, include = F, echo = F}
ds_table <- read.csv("data-sources-table.csv", colClasses = "character")
ds_table_test <- ds_table %>%
  select(Source, Type, Agency)
```
```{r pressure, echo=FALSE}
datatable(ds_table, rownames = F, 
          caption = "Table 1: Data Sources",
          width = "600px",
          options = list(
  searching = F,
  pageLength = 5,
  lengthMenu = c(5, 10, 15, 20),
  scrollX = "600px"
)) %>%
  DT::formatStyle(columns = c("Source", "Type", "Agency", "Detection.Type", "Available.Granularity",
                              "Date.Range", "Accessibility", "Location.Availability", "Installation.Type", "Collection.Frequency",
                              "Documentation"), fontSize = '10px')
```

